services:
  il-boost:
    image: il-boost
    container_name: il-boost
    environment:
      CB_MODULE_ID: IL_COMMIT
      CB_CONFIG: /cb-config.toml 
      CB_SIGNER_JWT: ${JWT}
      METRICS_SERVER: 10000
      SIGNER_SERVER: cb_signer:20000
      ROLLING_DURATION: daily
      RUST_LOG: debug
      MAX_LOG_FILES: 30
      HOST_DOCKER_INTERNAL: host.docker.internal
    volumes:
    - ./cb-config.toml:/cb-config.toml:ro
    - ./logs:/var/logs/commit-boost
    networks:
    - monitoring_network
    - signer_network
    depends_on:
    - cb_signer
  cb_signer:
    image: commitboost_signer
    container_name: cb_signer
    environment:
      CB_CONFIG: /cb-config.toml 
      CB_JWTS: "{\"IL_COMMIT\":\"${JWT}\"}"
      METRICS_SERVER: 10000
      SIGNER_SERVER: 20000
      ROLLING_DURATION: daily
      RUST_LOG: debug
      MAX_LOG_FILES: 30
      CB_SIGNER_FILE: /keys.json
      SIGNER_LOADER_DIR_KEYS: /keys
      SIGNER_LOADER_DIR_SECRETS: /secrets
    volumes:
    - ./cb-config.toml:/cb-config.toml:ro
    - ./logs:/var/logs/commit-boost
    -  ${YOUR_PATH_TO_KEYS_DIR}:/keys:ro
    -  ${YOUR_PATH_TO_SERETS_DIR}:/secrets:ro
    networks:
    - monitoring_network
    - signer_network
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
networks:
  monitoring_network:
    driver: bridge
  signer_network:
    driver: bridge
